linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 50
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 5
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused
    - misspell

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - goconst

run:
  timeout: 5m
  modules-download-mode: readonly

output:
  sort-results: true
